__class_v3 = {0: 'tench, Tinca_tinca',
 1: 'goldfish, Carassius_auratus', 
 2: 'great_white_shark, white_shark, man-eater, man-eating_shark, Carcharodon_carcharias', 
 3: 'tiger_shark, Galeocerdo_cuvieri', 
 4: 'hammerhead, hammerhead_shark', 
 5: 'electric_ray, crampfish, numbfish, torpedo', 
 6: 'stingray', 
 7: 'cock', 
 8: 'hen', 
 9: 'ostrich, Struthio_camelus', 
 10: 'brambling, Fringilla_montifringilla', 
 11: 'goldfinch, Carduelis_carduelis', 
 12: 'house_finch, linnet, Carpodacus_mexicanus', 
 13: 'junco, snowbird', 
 14: 'indigo_bunting, indigo_finch, indigo_bird, Passerina_cyanea', 
 15: 'robin, American_robin, Turdus_migratorius', 
 16: 'bulbul', 
 17: 'jay', 
 18: 'magpie', 
 19: 'chickadee', 
 20: 'water_ouzel, dipper', 
 21: 'kite', 
 22: 'bald_eagle, American_eagle, Haliaeetus_leucocephalus', 
 23: 'vulture', 
 24: 'great_grey_owl, great_gray_owl, Strix_nebulosa', 
 25: 'European_fire_salamander, Salamandra_salamandra', 
 26: 'common_newt, Triturus_vulgaris', 
 27: 'eft', 
 28: 'spotted_salamander, Ambystoma_maculatum', 
 29: 'axolotl, mud_puppy, Ambystoma_mexicanum', 
 30: 'bullfrog, Rana_catesbeiana', 
 31: 'tree_frog, tree-frog', 
 32: 'tailed_frog, bell_toad, ribbed_toad, tailed_toad, Ascaphus_trui', 
 33: 'loggerhead, loggerhead_turtle, Caretta_caretta', 
 34: 'leatherback_turtle, leatherback, leathery_turtle, Dermochelys_coriacea', 
 35: 'mud_turtle', 
 36: 'terrapin', 
 37: 'box_turtle, box_tortoise', 
 38: 'banded_gecko', 
 39: 'common_iguana, iguana, Iguana_iguana', 
 40: 'American_chameleon, anole, Anolis_carolinensis', 
 41: 'whiptail, whiptail_lizard', 
 42: 'agama', 
 43: 'frilled_lizard, Chlamydosaurus_kingi', 
 44: 'alligator_lizard', 
 45: 'Gila_monster, Heloderma_suspectum', 
 46: 'green_lizard, Lacerta_viridis', 
 47: 'African_chameleon, Chamaeleo_chamaeleon', 
 48: 'Komodo_dragon, Komodo_lizard, dragon_lizard, giant_lizard, Varanus_komodoensis', 
 49: 'African_crocodile, Nile_crocodile, Crocodylus_niloticus', 
 50: 'American_alligator, Alligator_mississipiensis', 
 51: 'triceratops', 
 52: 'thunder_snake, worm_snake, Carphophis_amoenus', 
 53: 'ringneck_snake, ring-necked_snake, ring_snake', 
 54: 'hognose_snake, puff_adder, sand_viper', 
 55: 'green_snake, grass_snake', 
 56: 'king_snake, kingsnake', 
 57: 'garter_snake, grass_snake', 
 58: 'water_snake', 
 59: 'vine_snake', 
 60: 'night_snake, Hypsiglena_torquata', 
 61: 'boa_constrictor, Constrictor_constrictor', 
 62: 'rock_python, rock_snake, Python_sebae', 
 63: 'Indian_cobra, Naja_naja', 
 64: 'green_mamba', 
 65: 'sea_snake', 
 66: 'horned_viper, cerastes, sand_viper, horned_asp, Cerastes_cornutus', 
 67: 'diamondback, diamondback_rattlesnake, Crotalus_adamanteus', 
 68: 'sidewinder, horned_rattlesnake, Crotalus_cerastes', 
 69: 'trilobite', 
 70: 'harvestman, daddy_longlegs, Phalangium_opilio', 
 71: 'scorpion', 
 72: 'black_and_gold_garden_spider, Argiope_aurantia', 
 73: 'barn_spider, Araneus_cavaticus', 
 74: 'garden_spider, Aranea_diademata', 
 75: 'black_widow, Latrodectus_mactans', 
 76: 'tarantula', 
 77: 'wolf_spider, hunting_spider', 
 78: 'tick', 
 79: 'centipede', 
 80: 'black_grouse', 
 81: 'ptarmigan', 
 82: 'ruffed_grouse, partridge, Bonasa_umbellus', 
 83: 'prairie_chicken, prairie_grouse, prairie_fowl', 
 84: 'peacock', 
 85: 'quail', 
 86: 'partridge', 
 87: 'African_grey, African_gray, Psittacus_erithacus', 
 88: 'macaw', 
 89: 'sulphur-crested_cockatoo, Kakatoe_galerita, Cacatua_galerita', 
 90: 'lorikeet', 
 91: 'coucal', 
 92: 'bee_eater', 
 93: 'hornbill', 
 94: 'hummingbird', 
 95: 'jacamar', 
 96: 'toucan', 
 97: 'drake', 
 98: 'red-breasted_merganser, Mergus_serrator', 
 99: 'goose', 
 100: 'black_swan, Cygnus_atratus', 
 101: 'tusker', 
 102: 'echidna, spiny_anteater, anteater', 
 103: 'platypus, duckbill, duckbilled_platypus, duck-billed_platypus, Ornithorhynchus_anatinus', 
 104: 'wallaby, brush_kangaroo', 
 105: 'koala, koala_bear, kangaroo_bear, native_bear, Phascolarctos_cinereus', 
 106: 'wombat', 
 107: 'jellyfish', 
 108: 'sea_anemone, anemone', 
 109: 'brain_coral', 
 110: 'flatworm, platyhelminth', 
 111: 'nematode, nematode_worm, roundworm', 
 112: 'conch', 
 113: 'snail', 
 114: 'slug', 
 115: 'sea_slug, nudibranch', 
 116: 'chiton, coat-of-mail_shell, sea_cradle, polyplacophore', 
 117: 'chambered_nautilus, pearly_nautilus, nautilus', 
 118: 'Dungeness_crab, Cancer_magister', 
 119: 'rock_crab, Cancer_irroratus', 
 120: 'fiddler_crab', 
 121: 'king_crab, Alaska_crab, Alaskan_king_crab, Alaska_king_crab, Paralithodes_camtschatica', 
 122: 'American_lobster, Northern_lobster, Maine_lobster, Homarus_americanus', 
 123: 'spiny_lobster, langouste, rock_lobster, crawfish, crayfish, sea_crawfish', 
 124: 'crayfish, crawfish, crawdad, crawdaddy', 
 125: 'hermit_crab', 
 126: 'isopod', 
 127: 'white_stork, Ciconia_ciconia', 
 128: 'black_stork, Ciconia_nigra', 
 129: 'spoonbill', 
 130: 'flamingo', 
 131: 'little_blue_heron, Egretta_caerulea', 
 132: 'American_egret, great_white_heron, Egretta_albus', 
 133: 'bittern', 
 134: 'crane', 
 135: 'limpkin, Aramus_pictus', 
 136: 'European_gallinule, Porphyrio_porphyrio', 
 137: 'American_coot, marsh_hen, mud_hen, water_hen, Fulica_americana', 
 138: 'bustard', 
 139: 'ruddy_turnstone, Arenaria_interpres', 
 140: 'red-backed_sandpiper, dunlin, Erolia_alpina', 
 141: 'redshank, Tringa_totanus', 
 142: 'dowitcher', 
 143: 'oystercatcher, oyster_catcher', 
 144: 'pelican', 
 145: 'king_penguin, Aptenodytes_patagonica', 
 146: 'albatross, mollymawk', 
 147: 'grey_whale, gray_whale, devilfish, Eschrichtius_gibbosus, Eschrichtius_robustus', 
 148: 'killer_whale, killer, orca, grampus, sea_wolf, Orcinus_orca', 
 149: 'dugong, Dugong_dugon', 
 150: 'sea_lion', 
 151: 'Chihuahua', 
 152: 'Japanese_spaniel', 
 153: 'Maltese_dog, Maltese_terrier, Maltese', 
 154: 'Pekinese, Pekingese, Peke', 
 155: 'Shih-Tzu', 
 156: 'Blenheim_spaniel', 
 157: 'papillon', 
 158: 'toy_terrier', 
 159: 'Rhodesian_ridgeback', 
 160: 'Afghan_hound, Afghan', 
 161: 'basset, basset_hound', 
 162: 'beagle', 
 163: 'bloodhound, sleuthhound', 
 164: 'bluetick', 
 165: 'black-and-tan_coonhound', 
 166: 'Walker_hound, Walker_foxhound', 
 167: 'English_foxhound', 
 168: 'redbone', 
 169: 'borzoi, Russian_wolfhound', 
 170: 'Irish_wolfhound', 
 171: 'Italian_greyhound', 
 172: 'whippet', 
 173: 'Ibizan_hound, Ibizan_Podenco', 
 174: 'Norwegian_elkhound, elkhound', 
 175: 'otterhound, otter_hound', 
 176: 'Saluki, gazelle_hound', 
 177: 'Scottish_deerhound, deerhound', 
 178: 'Weimaraner', 
 179: 'Staffordshire_bullterrier, Staffordshire_bull_terrier', 
 180: 'American_Staffordshire_terrier, Staffordshire_terrier, American_pit_bull_terrier, pit_bull_terrier', 
 181: 'Bedlington_terrier', 
 182: 'Border_terrier', 
 183: 'Kerry_blue_terrier', 
 184: 'Irish_terrier', 
 185: 'Norfolk_terrier', 
 186: 'Norwich_terrier', 
 187: 'Yorkshire_terrier', 
 188: 'wire-haired_fox_terrier', 
 189: 'Lakeland_terrier', 
 190: 'Sealyham_terrier, Sealyham', 
 191: 'Airedale, Airedale_terrier', 
 192: 'cairn, cairn_terrier', 
 193: 'Australian_terrier', 
 194: 'Dandie_Dinmont, Dandie_Dinmont_terrier', 
 195: 'Boston_bull, Boston_terrier', 
 196: 'miniature_schnauzer', 
 197: 'giant_schnauzer', 
 198: 'standard_schnauzer', 
 199: 'Scotch_terrier, Scottish_terrier, Scottie', 
 200: 'Tibetan_terrier, chrysanthemum_dog', 
 201: 'silky_terrier, Sydney_silky', 
 202: 'soft-coated_wheaten_terrier', 
 203: 'West_Highland_white_terrier', 
 204: 'Lhasa, Lhasa_apso', 
 205: 'flat-coated_retriever', 
 206: 'curly-coated_retriever', 
 207: 'golden_retriever', 
 208: 'Labrador_retriever', 
 209: 'Chesapeake_Bay_retriever', 
 210: 'German_short-haired_pointer', 
 211: 'vizsla, Hungarian_pointer', 
 212: 'English_setter', 
 213: 'Irish_setter, red_setter', 
 214: 'Gordon_setter', 
 215: 'Brittany_spaniel', 
 216: 'clumber, clumber_spaniel', 
 217: 'English_springer, English_springer_spaniel', 
 218: 'Welsh_springer_spaniel', 
 219: 'cocker_spaniel, English_cocker_spaniel, cocker', 
 220: 'Sussex_spaniel', 
 221: 'Irish_water_spaniel', 
 222: 'kuvasz', 
 223: 'schipperke', 
 224: 'groenendael', 
 225: 'malinois', 
 226: 'briard', 
 227: 'kelpie', 
 228: 'komondor', 
 229: 'Old_English_sheepdog, bobtail', 
 230: 'Shetland_sheepdog, Shetland_sheep_dog, Shetland', 
 231: 'collie', 
 232: 'Border_collie', 
 233: 'Bouvier_des_Flandres, Bouviers_des_Flandres', 
 234: 'Rottweiler', 
 235: 'German_shepherd, German_shepherd_dog, German_police_dog, alsatian', 
 236: 'Doberman, Doberman_pinscher', 
 237: 'miniature_pinscher', 
 238: 'Greater_Swiss_Mountain_dog', 
 239: 'Bernese_mountain_dog', 
 240: 'Appenzeller', 
 241: 'EntleBucher', 
 242: 'boxer', 
 243: 'bull_mastiff', 
 244: 'Tibetan_mastiff', 
 245: 'French_bulldog', 
 246: 'Great_Dane', 
 247: 'Saint_Bernard, St_Bernard', 
 248: 'Eskimo_dog, husky', 
 249: 'malamute, malemute, Alaskan_malamute', 
 250: 'Siberian_husky', 
 251: 'dalmatian, coach_dog, carriage_dog', 
 252: 'affenpinscher, monkey_pinscher, monkey_dog', 
 253: 'basenji', 
 254: 'pug, pug-dog', 
 255: 'Leonberg', 
 256: 'Newfoundland, Newfoundland_dog', 
 257: 'Great_Pyrenees', 
 258: 'Samoyed, Samoyede', 
 259: 'Pomeranian', 
 260: 'chow, chow_chow', 
 261: 'keeshond', 
 262: 'Brabancon_griffon', 
 263: 'Pembroke, Pembroke_Welsh_corgi', 
 264: 'Cardigan, Cardigan_Welsh_corgi', 
 265: 'toy_poodle', 
 266: 'miniature_poodle', 
 267: 'standard_poodle', 
 268: 'Mexican_hairless', 
 269: 'timber_wolf, grey_wolf, gray_wolf, Canis_lupus', 
 270: 'white_wolf, Arctic_wolf, Canis_lupus_tundrarum', 
 271: 'red_wolf, maned_wolf, Canis_rufus, Canis_niger', 
 272: 'coyote, prairie_wolf, brush_wolf, Canis_latrans', 
 273: 'dingo, warrigal, warragal, Canis_dingo', 
 274: 'dhole, Cuon_alpinus', 
 275: 'African_hunting_dog, hyena_dog, Cape_hunting_dog, Lycaon_pictus', 
 276: 'hyena, hyaena', 
 277: 'red_fox, Vulpes_vulpes', 
 278: 'kit_fox, Vulpes_macrotis', 
 279: 'Arctic_fox, white_fox, Alopex_lagopus', 
 280: 'grey_fox, gray_fox, Urocyon_cinereoargenteus', 
 281: 'tabby, tabby_cat', 
 282: 'tiger_cat', 
 283: 'Persian_cat', 
 284: 'Siamese_cat, Siamese', 
 285: 'Egyptian_cat', 
 286: 'cougar, puma, catamount, mountain_lion, painter, panther, Felis_concolor', 
 287: 'lynx, catamount', 
 288: 'leopard, Panthera_pardus', 
 289: 'snow_leopard, ounce, Panthera_uncia', 
 290: 'jaguar, panther, Panthera_onca, Felis_onca', 
 291: 'lion, king_of_beasts, Panthera_leo', 
 292: 'tiger, Panthera_tigris', 
 293: 'cheetah, chetah, Acinonyx_jubatus', 
 294: 'brown_bear, bruin, Ursus_arctos', 
 295: 'American_black_bear, black_bear, Ursus_americanus, Euarctos_americanus', 
 296: 'ice_bear, polar_bear, Ursus_Maritimus, Thalarctos_maritimus', 
 297: 'sloth_bear, Melursus_ursinus, Ursus_ursinus', 
 298: 'mongoose', 
 299: 'meerkat, mierkat', 
 300: 'tiger_beetle', 
 301: 'ladybug, ladybeetle, lady_beetle, ladybird, ladybird_beetle', 
 302: 'ground_beetle, carabid_beetle', 
 303: 'long-horned_beetle, longicorn, longicorn_beetle', 
 304: 'leaf_beetle, chrysomelid', 
 305: 'dung_beetle', 
 306: 'rhinoceros_beetle', 
 307: 'weevil', 
 308: 'fly', 
 309: 'bee', 
 310: 'ant, emmet, pismire', 
 311: 'grasshopper, hopper', 
 312: 'cricket', 
 313: 'walking_stick, walkingstick, stick_insect', 
 314: 'cockroach, roach', 
 315: 'mantis, mantid', 
 316: 'cicada, cicala', 
 317: 'leafhopper', 
 318: 'lacewing, lacewing_fly', 
 319: "dragonfly, darning_needle, devil's_darning_needle, sewing_needle, snake_feeder, snake_doctor, mosquito_hawk, skeeter_hawk", 
 320: 'damselfly', 
 321: 'admiral', 
 322: 'ringlet, ringlet_butterfly', 
 323: 'monarch, monarch_butterfly, milkweed_butterfly, Danaus_plexippus', 
 324: 'cabbage_butterfly', 
 325: 'sulphur_butterfly, sulfur_butterfly', 
 326: 'lycaenid, lycaenid_butterfly', 
 327: 'starfish, sea_star', 
 328: 'sea_urchin', 
 329: 'sea_cucumber, holothurian', 
 330: 'wood_rabbit, cottontail, cottontail_rabbit', 
 331: 'hare', 
 332: 'Angora, Angora_rabbit', 
 333: 'hamster', 
 334: 'porcupine, hedgehog', 
 335: 'fox_squirrel, eastern_fox_squirrel, Sciurus_niger', 
 336: 'marmot', 
 337: 'beaver', 
 338: 'guinea_pig, Cavia_cobaya', 
 339: 'sorrel', 
 340: 'zebra', 
 341: 'hog, pig, grunter, squealer, Sus_scrofa', 
 342: 'wild_boar, boar, Sus_scrofa', 
 343: 'warthog', 
 344: 'hippopotamus, hippo, river_horse, Hippopotamus_amphibius', 
 345: 'ox', 
 346: 'water_buffalo, water_ox, Asiatic_buffalo, Bubalus_bubalis', 
 347: 'bison', 
 348: 'ram, tup', 
 349: 'bighorn, bighorn_sheep, cimarron, Rocky_Mountain_bighorn, Rocky_Mountain_sheep, Ovis_canadensis', 
 350: 'ibex, Capra_ibex', 
 351: 'hartebeest', 
 352: 'impala, Aepyceros_melampus', 
 353: 'gazelle', 
 354: 'Arabian_camel, dromedary, Camelus_dromedarius', 
 355: 'llama', 
 356: 'weasel', 
 357: 'mink', 
 358: 'polecat, fitch, foulmart, foumart, Mustela_putorius', 
 359: 'black-footed_ferret, ferret, Mustela_nigripes', 
 360: 'otter', 
 361: 'skunk, polecat, wood_pussy', 
 362: 'badger', 
 363: 'armadillo', 
 364: 'three-toed_sloth, ai, Bradypus_tridactylus', 
 365: 'orangutan, orang, orangutang, Pongo_pygmaeus', 
 366: 'gorilla, Gorilla_gorilla', 
 367: 'chimpanzee, chimp, Pan_troglodytes', 
 368: 'gibbon, Hylobates_lar', 
 369: 'siamang, Hylobates_syndactylus, Symphalangus_syndactylus', 
 370: 'guenon, guenon_monkey', 
 371: 'patas, hussar_monkey, Erythrocebus_patas', 
 372: 'baboon', 
 373: 'macaque', 
 374: 'langur', 
 375: 'colobus, colobus_monkey', 
 376: 'proboscis_monkey, Nasalis_larvatus', 
 377: 'marmoset', 
 378: 'capuchin, ringtail, Cebus_capucinus', 
 379: 'howler_monkey, howler', 
 380: 'titi, titi_monkey', 
 381: 'spider_monkey, Ateles_geoffroyi', 
 382: 'squirrel_monkey, Saimiri_sciureus', 
 383: 'Madagascar_cat, ring-tailed_lemur, Lemur_catta', 
 384: 'indri, indris, Indri_indri, Indri_brevicaudatus', 
 385: 'Indian_elephant, Elephas_maximus', 
 386: 'African_elephant, Loxodonta_africana', 
 387: 'lesser_panda, red_panda, panda, bear_cat, cat_bear, Ailurus_fulgens', 
 388: 'giant_panda, panda, panda_bear, coon_bear, Ailuropoda_melanoleuca', 
 389: 'barracouta, snoek', 
 390: 'eel', 
 391: 'coho, cohoe, coho_salmon, blue_jack, silver_salmon, Oncorhynchus_kisutch', 
 392: 'rock_beauty, Holocanthus_tricolor', 
 393: 'anemone_fish', 
 394: 'sturgeon', 
 395: 'gar, garfish, garpike, billfish, Lepisosteus_osseus', 
 396: 'lionfish', 
 397: 'puffer, pufferfish, blowfish, globefish', 
 398: 'abacus', 
 399: 'abaya', 
 400: "academic_gown, academic_robe, judge's_robe", 
 401: 'accordion, piano_accordion, squeeze_box', 
 402: 'acoustic_guitar', 
 403: 'aircraft_carrier, carrier, flattop, attack_aircraft_carrier', 
 404: 'airliner', 
 405: 'airship, dirigible', 
 406: 'altar', 
 407: 'ambulance', 
 408: 'amphibian, amphibious_vehicle', 
 409: 'analog_clock', 
 410: 'apiary, bee_house', 
 411: 'apron', 
 412: 'ashcan, trash_can, garbage_can, wastebin, ash_bin, ash-bin, ashbin, dustbin, trash_barrel, trash_bin', 
 413: 'assault_rifle, assault_gun', 
 414: 'backpack, back_pack, knapsack, packsack, rucksack, haversack', 
 415: 'bakery, bakeshop, bakehouse', 
 416: 'balance_beam, beam', 
 417: 'balloon', 
 418: 'ballpoint, ballpoint_pen, ballpen, Biro', 
 419: 'Band_Aid', 
 420: 'banjo', 
 421: 'bannister, banister, balustrade, balusters, handrail', 
 422: 'barbell', 
 423: 'barber_chair', 
 424: 'barbershop', 
 425: 'barn', 
 426: 'barometer', 
 427: 'barrel, cask', 
 428: 'barrow, garden_cart, lawn_cart, wheelbarrow', 
 429: 'baseball', 
 430: 'basketball', 
 431: 'bassinet', 
 432: 'bassoon', 
 433: 'bathing_cap, swimming_cap', 
 434: 'bath_towel', 
 435: 'bathtub, bathing_tub, bath, tub', 
 436: 'beach_wagon, station_wagon, wagon, estate_car, beach_waggon, station_waggon, waggon', 
 437: 'beacon, lighthouse, beacon_light, pharos', 
 438: 'beaker', 
 439: 'bearskin, busby, shako', 
 440: 'beer_bottle', 
 441: 'beer_glass', 
 442: 'bell_cote, bell_cot', 
 443: 'bib', 
 444: 'bicycle-built-for-two, tandem_bicycle, tandem', 
 445: 'bikini, two-piece', 
 446: 'binder, ring-binder', 
 447: 'binoculars, field_glasses, opera_glasses', 
 448: 'birdhouse', 
 449: 'boathouse', 
 450: 'bobsled, bobsleigh, bob', 
 451: 'bolo_tie, bolo, bola_tie, bola', 
 452: 'bonnet, poke_bonnet', 
 453: 'bookcase', 
 454: 'bookshop, bookstore, bookstall', 
 455: 'bottlecap', 
 456: 'bow', 
 457: 'bow_tie, bow-tie, bowtie', 
 458: 'brass, memorial_tablet, plaque', 
 459: 'brassiere, bra, bandeau', 
 460: 'breakwater, groin, groyne, mole, bulwark, seawall, jetty', 
 461: 'breastplate, aegis, egis', 
 462: 'broom', 
 463: 'bucket, pail', 
 464: 'buckle', 
 465: 'bulletproof_vest', 
 466: 'bullet_train, bullet', 
 467: 'butcher_shop, meat_market', 
 468: 'cab, hack, taxi, taxicab', 
 469: 'caldron, cauldron', 
 470: 'candle, taper, wax_light', 
 471: 'cannon', 
 472: 'canoe', 
 473: 'can_opener, tin_opener', 
 474: 'cardigan', 
 475: 'car_mirror', 
 476: 'carousel, carrousel, merry-go-round, roundabout, whirligig', 
 477: "carpenter's_kit, tool_kit", 
 478: 'carton', 
 479: 'car_wheel', 
 480: 'cash_machine, cash_dispenser, automated_teller_machine, automatic_teller_machine, automated_teller, automatic_teller, ATM', 
 481: 'cassette', 
 482: 'cassette_player', 
 483: 'castle', 
 484: 'catamaran', 
 485: 'CD_player', 
 486: 'cello, violoncello', 
 487: 'cellular_telephone, cellular_phone, cellphone, cell, mobile_phone', 
 488: 'chain', 
 489: 'chainlink_fence', 
 490: 'chain_mail, ring_mail, mail, chain_armor, chain_armour, ring_armor, ring_armour', 
 491: 'chain_saw, chainsaw', 
 492: 'chest', 
 493: 'chiffonier, commode', 
 494: 'chime, bell, gong', 
 495: 'china_cabinet, china_closet', 
 496: 'Christmas_stocking', 
 497: 'church, church_building', 
 498: 'cinema, movie_theater, movie_theatre, movie_house, picture_palace', 
 499: 'cleaver, meat_cleaver, chopper', 
 500: 'cliff_dwelling', 
 501: 'cloak', 
 502: 'clog, geta, patten, sabot', 
 503: 'cocktail_shaker', 
 504: 'coffee_mug', 
 505: 'coffeepot', 
 506: 'coil, spiral, volute, whorl, helix', 
 507: 'combination_lock', 
 508: 'computer_keyboard, keypad', 
 509: 'confectionery, confectionary, candy_store', 
 510: 'container_ship, containership, container_vessel', 
 511: 'convertible', 
 512: 'corkscrew, bottle_screw', 
 513: 'cornet, horn, trumpet, trump', 
 514: 'cowboy_boot', 
 515: 'cowboy_hat, ten-gallon_hat', 
 516: 'cradle', 
 517: 'crane', 
 518: 'crash_helmet', 
 519: 'crate', 
 520: 'crib, cot', 
 521: 'Crock_Pot', 
 522: 'croquet_ball', 
 523: 'crutch', 
 524: 'cuirass', 
 525: 'dam, dike, dyke', 
 526: 'desk', 
 527: 'desktop_computer', 
 528: 'dial_telephone, dial_phone', 
 529: 'diaper, nappy, napkin', 
 530: 'digital_clock', 
 531: 'digital_watch', 
 532: 'dining_table, board', 
 533: 'dishrag, dishcloth', 
 534: 'dishwasher, dish_washer, dishwashing_machine', 
 535: 'disk_brake, disc_brake', 
 536: 'dock, dockage, docking_facility', 
 537: 'dogsled, dog_sled, dog_sleigh', 
 538: 'dome', 
 539: 'doormat, welcome_mat', 
 540: 'drilling_platform, offshore_rig', 
 541: 'drum, membranophone, tympan', 
 542: 'drumstick', 
 543: 'dumbbell', 
 544: 'Dutch_oven', 
 545: 'electric_fan, blower', 
 546: 'electric_guitar', 
 547: 'electric_locomotive', 
 548: 'entertainment_center', 
 549: 'envelope', 
 550: 'espresso_maker', 
 551: 'face_powder', 
 552: 'feather_boa, boa', 
 553: 'file, file_cabinet, filing_cabinet', 
 554: 'fireboat', 
 555: 'fire_engine, fire_truck', 
 556: 'fire_screen, fireguard', 
 557: 'flagpole, flagstaff', 
 558: 'flute, transverse_flute', 
 559: 'folding_chair', 
 560: 'football_helmet', 
 561: 'forklift', 
 562: 'fountain', 
 563: 'fountain_pen', 
 564: 'four-poster', 
 565: 'freight_car', 
 566: 'French_horn, horn', 
 567: 'frying_pan, frypan, skillet', 
 568: 'fur_coat', 
 569: 'garbage_truck, dustcart', 
 570: 'gasmask, respirator, gas_helmet', 
 571: 'gas_pump, gasoline_pump, petrol_pump, island_dispenser', 
 572: 'goblet', 
 573: 'go-kart', 
 574: 'golf_ball', 
 575: 'golfcart, golf_cart', 
 576: 'gondola', 
 577: 'gong, tam-tam', 
 578: 'gown', 
 579: 'grand_piano, grand', 
 580: 'greenhouse, nursery, glasshouse', 
 581: 'grille, radiator_grille', 
 582: 'grocery_store, grocery, food_market, market', 
 583: 'guillotine', 
 584: 'hair_slide', 
 585: 'hair_spray', 
 586: 'half_track', 
 587: 'hammer', 
 588: 'hamper', 
 589: 'hand_blower, blow_dryer, blow_drier, hair_dryer, hair_drier', 
 590: 'hand-held_computer, hand-held_microcomputer', 
 591: 'handkerchief, hankie, hanky, hankey', 
 592: 'hard_disc, hard_disk, fixed_disk', 
 593: 'harmonica, mouth_organ, harp, mouth_harp', 
 594: 'harp', 
 595: 'harvester, reaper', 
 596: 'hatchet', 
 597: 'holster', 
 598: 'home_theater, home_theatre', 
 599: 'honeycomb', 
 600: 'hook, claw', 
 601: 'hoopskirt, crinoline', 
 602: 'horizontal_bar, high_bar', 
 603: 'horse_cart, horse-cart', 
 604: 'hourglass', 
 605: 'iPod', 
 606: 'iron, smoothing_iron', 
 607: "jack-o'-lantern", 
 608: 'jean, blue_jean, denim', 
 609: 'jeep, landrover', 
 610: 'jersey, T-shirt, tee_shirt', 
 611: 'jigsaw_puzzle', 
 612: 'jinrikisha, ricksha, rickshaw', 
 613: 'joystick', 
 614: 'kimono', 
 615: 'knee_pad', 
 616: 'knot', 
 617: 'lab_coat, laboratory_coat', 
 618: 'ladle', 
 619: 'lampshade, lamp_shade', 
 620: 'laptop, laptop_computer', 
 621: 'lawn_mower, mower', 
 622: 'lens_cap, lens_cover', 
 623: 'letter_opener, paper_knife, paperknife', 
 624: 'library', 
 625: 'lifeboat', 
 626: 'lighter, light, igniter, ignitor', 
 627: 'limousine, limo', 
 628: 'liner, ocean_liner', 
 629: 'lipstick, lip_rouge', 
 630: 'Loafer', 
 631: 'lotion', 
 632: 'loudspeaker, speaker, speaker_unit, loudspeaker_system, speaker_system', 
 633: "loupe, jeweler's_loupe", 
 634: 'lumbermill, sawmill', 
 635: 'magnetic_compass', 
 636: 'mailbag, postbag', 
 637: 'mailbox, letter_box', 
 638: 'maillot', 
 639: 'maillot, tank_suit', 
 640: 'manhole_cover', 
 641: 'maraca', 
 642: 'marimba, xylophone', 
 643: 'mask', 
 644: 'matchstick', 
 645: 'maypole', 
 646: 'maze, labyrinth', 
 647: 'measuring_cup', 
 648: 'medicine_chest, medicine_cabinet', 
 649: 'megalith, megalithic_structure', 
 650: 'microphone, mike', 
 651: 'microwave, microwave_oven', 
 652: 'military_uniform', 
 653: 'milk_can', 
 654: 'minibus', 
 655: 'miniskirt, mini', 
 656: 'minivan', 
 657: 'missile', 
 658: 'mitten', 
 659: 'mixing_bowl', 
 660: 'mobile_home, manufactured_home', 
 661: 'Model_T', 
 662: 'modem', 
 663: 'monastery', 
 664: 'monitor', 
 665: 'moped', 
 666: 'mortar', 
 667: 'mortarboard', 
 668: 'mosque', 
 669: 'mosquito_net', 
 670: 'motor_scooter, scooter', 
 671: 'mountain_bike, all-terrain_bike, off-roader', 
 672: 'mountain_tent', 
 673: 'mouse, computer_mouse', 
 674: 'mousetrap', 
 675: 'moving_van', 
 676: 'muzzle', 
 677: 'nail', 
 678: 'neck_brace', 
 679: 'necklace', 
 680: 'nipple', 
 681: 'notebook, notebook_computer', 
 682: 'obelisk', 
 683: 'oboe, hautboy, hautbois', 
 684: 'ocarina, sweet_potato', 
 685: 'odometer, hodometer, mileometer, milometer', 
 686: 'oil_filter', 
 687: 'organ, pipe_organ', 
 688: 'oscilloscope, scope, cathode-ray_oscilloscope, CRO', 
 689: 'overskirt', 
 690: 'oxcart', 
 691: 'oxygen_mask', 
 692: 'packet', 
 693: 'paddle, boat_paddle', 
 694: 'paddlewheel, paddle_wheel', 
 695: 'padlock', 
 696: 'paintbrush', 
 697: "pajama, pyjama, pj's, jammies", 
 698: 'palace', 
 699: 'panpipe, pandean_pipe, syrinx', 
 700: 'paper_towel', 
 701: 'parachute, chute', 
 702: 'parallel_bars, bars', 
 703: 'park_bench', 
 704: 'parking_meter', 
 705: 'passenger_car, coach, carriage', 
 706: 'patio, terrace', 
 707: 'pay-phone, pay-station', 
 708: 'pedestal, plinth, footstall', 
 709: 'pencil_box, pencil_case', 
 710: 'pencil_sharpener', 
 711: 'perfume, essence', 
 712: 'Petri_dish', 
 713: 'photocopier', 
 714: 'pick, plectrum, plectron', 
 715: 'pickelhaube', 
 716: 'picket_fence, paling', 
 717: 'pickup, pickup_truck', 
 718: 'pier', 
 719: 'piggy_bank, penny_bank', 
 720: 'pill_bottle', 
 721: 'pillow', 
 722: 'ping-pong_ball', 
 723: 'pinwheel', 
 724: 'pirate, pirate_ship', 
 725: 'pitcher, ewer', 
 726: "plane, carpenter's_plane, woodworking_plane", 
 727: 'planetarium', 
 728: 'plastic_bag', 
 729: 'plate_rack', 
 730: 'plow, plough', 
 731: "plunger, plumber's_helper", 
 732: 'Polaroid_camera, Polaroid_Land_camera', 
 733: 'pole', 
 734: 'police_van, police_wagon, paddy_wagon, patrol_wagon, wagon, black_Maria', 
 735: 'poncho', 
 736: 'pool_table, billiard_table, snooker_table', 
 737: 'pop_bottle, soda_bottle', 
 738: 'pot, flowerpot', 
 739: "potter's_wheel", 
 740: 'power_drill', 
 741: 'prayer_rug, prayer_mat', 
 742: 'printer', 
 743: 'prison, prison_house', 
 744: 'projectile, missile', 
 745: 'projector', 
 746: 'puck, hockey_puck', 
 747: 'punching_bag, punch_bag, punching_ball, punchball', 
 748: 'purse', 
 749: 'quill, quill_pen', 
 750: 'quilt, comforter, comfort, puff', 
 751: 'racer, race_car, racing_car', 
 752: 'racket, racquet', 
 753: 'radiator', 
 754: 'radio, wireless', 
 755: 'radio_telescope, radio_reflector', 
 756: 'rain_barrel', 
 757: 'recreational_vehicle, RV, R.V.', 
 758: 'reel', 
 759: 'reflex_camera', 
 760: 'refrigerator, icebox', 
 761: 'remote_control, remote', 
 762: 'restaurant, eating_house, eating_place, eatery', 
 763: 'revolver, six-gun, six-shooter', 
 764: 'rifle', 
 765: 'rocking_chair, rocker', 
 766: 'rotisserie', 
 767: 'rubber_eraser, rubber, pencil_eraser', 
 768: 'rugby_ball', 
 769: 'rule, ruler', 
 770: 'running_shoe', 
 771: 'safe', 
 772: 'safety_pin', 
 773: 'saltshaker, salt_shaker', 
 774: 'sandal', 
 775: 'sarong', 
 776: 'sax, saxophone', 
 777: 'scabbard', 
 778: 'scale, weighing_machine', 
 779: 'school_bus', 
 780: 'schooner', 
 781: 'scoreboard', 
 782: 'screen, CRT_screen', 
 783: 'screw', 
 784: 'screwdriver', 
 785: 'seat_belt, seatbelt', 
 786: 'sewing_machine', 
 787: 'shield, buckler', 
 788: 'shoe_shop, shoe-shop, shoe_store', 
 789: 'shoji', 
 790: 'shopping_basket', 
 791: 'shopping_cart', 
 792: 'shovel', 
 793: 'shower_cap', 
 794: 'shower_curtain', 
 795: 'ski', 
 796: 'ski_mask', 
 797: 'sleeping_bag', 
 798: 'slide_rule, slipstick', 
 799: 'sliding_door', 
 800: 'slot, one-armed_bandit', 
 801: 'snorkel', 
 802: 'snowmobile', 
 803: 'snowplow, snowplough', 
 804: 'soap_dispenser', 
 805: 'soccer_ball', 
 806: 'sock', 
 807: 'solar_dish, solar_collector, solar_furnace', 
 808: 'sombrero', 
 809: 'soup_bowl', 
 810: 'space_bar', 
 811: 'space_heater', 
 812: 'space_shuttle', 
 813: 'spatula', 
 814: 'speedboat', 
 815: "spider_web, spider's_web", 
 816: 'spindle', 
 817: 'sports_car, sport_car', 
 818: 'spotlight, spot', 
 819: 'stage', 
 820: 'steam_locomotive', 
 821: 'steel_arch_bridge', 
 822: 'steel_drum', 
 823: 'stethoscope', 
 824: 'stole', 
 825: 'stone_wall', 
 826: 'stopwatch, stop_watch', 
 827: 'stove', 
 828: 'strainer', 
 829: 'streetcar, tram, tramcar, trolley, trolley_car', 
 830: 'stretcher', 
 831: 'studio_couch, day_bed', 
 832: 'stupa, tope', 
 833: 'submarine, pigboat, sub, U-boat', 
 834: 'suit, suit_of_clothes', 
 835: 'sundial', 
 836: 'sunglass', 
 837: 'sunglasses, dark_glasses, shades', 
 838: 'sunscreen, sunblock, sun_blocker', 
 839: 'suspension_bridge', 
 840: 'swab, swob, mop', 
 841: 'sweatshirt', 
 842: 'swimming_trunks, bathing_trunks', 
 843: 'swing', 
 844: 'switch, electric_switch, electrical_switch', 
 845: 'syringe', 
 846: 'table_lamp', 
 847: 'tank, army_tank, armored_combat_vehicle, armoured_combat_vehicle', 
 848: 'tape_player', 
 849: 'teapot', 
 850: 'teddy, teddy_bear', 
 851: 'television, television_system', 
 852: 'tennis_ball', 
 853: 'thatch, thatched_roof', 
 854: 'theater_curtain, theatre_curtain', 
 855: 'thimble', 
 856: 'thresher, thrasher, threshing_machine', 
 857: 'throne', 
 858: 'tile_roof', 
 859: 'toaster', 
 860: 'tobacco_shop, tobacconist_shop, tobacconist', 
 861: 'toilet_seat', 
 862: 'torch', 
 863: 'totem_pole', 
 864: 'tow_truck, tow_car, wrecker', 
 865: 'toyshop', 
 866: 'tractor', 
 867: 'trailer_truck, tractor_trailer, trucking_rig, rig, articulated_lorry, semi', 
 868: 'tray', 
 869: 'trench_coat', 
 870: 'tricycle, trike, velocipede', 
 871: 'trimaran', 
 872: 'tripod', 
 873: 'triumphal_arch', 
 874: 'trolleybus, trolley_coach, trackless_trolley', 
 875: 'trombone', 
 876: 'tub, vat', 
 877: 'turnstile', 
 878: 'typewriter_keyboard', 
 879: 'umbrella', 
 880: 'unicycle, monocycle', 
 881: 'upright, upright_piano', 
 882: 'vacuum, vacuum_cleaner', 
 883: 'vase', 
 884: 'vault', 
 885: 'velvet', 
 886: 'vending_machine', 
 887: 'vestment', 
 888: 'viaduct', 
 889: 'violin, fiddle', 
 890: 'volleyball', 
 891: 'waffle_iron', 
 892: 'wall_clock', 
 893: 'wallet, billfold, notecase, pocketbook', 
 894: 'wardrobe, closet, press', 
 895: 'warplane, military_plane', 
 896: 'washbasin, handbasin, washbowl, lavabo, wash-hand_basin', 
 897: 'washer, automatic_washer, washing_machine', 
 898: 'water_bottle', 
 899: 'water_jug', 
 900: 'water_tower', 
 901: 'whiskey_jug', 
 902: 'whistle', 
 903: 'wig', 
 904: 'window_screen', 
 905: 'window_shade', 
 906: 'Windsor_tie', 
 907: 'wine_bottle', 
 908: 'wing', 
 909: 'wok', 
 910: 'wooden_spoon', 
 911: 'wool, woolen, woollen', 
 912: 'worm_fence, snake_fence, snake-rail_fence, Virginia_fence', 
 913: 'wreck', 
 914: 'yawl', 
 915: 'yurt', 
 916: 'web_site, website, internet_site, site', 
 917: 'comic_book', 
 918: 'crossword_puzzle, crossword', 
 919: 'street_sign', 
 920: 'traffic_light, traffic_signal, stoplight', 
 921: 'book_jacket, dust_cover, dust_jacket, dust_wrapper', 
 922: 'menu', 
 923: 'plate', 
 924: 'guacamole', 
 925: 'consomme', 
 926: 'hot_pot, hotpot', 
 927: 'trifle', 
 928: 'ice_cream, icecream', 
 929: 'ice_lolly, lolly, lollipop, popsicle', 
 930: 'French_loaf', 
 931: 'bagel, beigel', 
 932: 'pretzel', 
 933: 'cheeseburger', 
 934: 'hotdog, hot_dog, red_hot', 
 935: 'mashed_potato', 
 936: 'head_cabbage', 
 937: 'broccoli', 
 938: 'cauliflower', 
 939: 'zucchini, courgette', 
 940: 'spaghetti_squash', 
 941: 'acorn_squash', 
 942: 'butternut_squash', 
 943: 'cucumber, cuke', 
 944: 'artichoke, globe_artichoke', 
 945: 'bell_pepper', 
 946: 'cardoon', 
 947: 'mushroom', 
 948: 'Granny_Smith', 
 949: 'strawberry', 
 950: 'orange', 
 951: 'lemon', 
 952: 'fig', 
 953: 'pineapple, ananas', 
 954: 'banana', 
 955: 'jackfruit, jak, jack', 
 956: 'custard_apple', 
 957: 'pomegranate', 
 958: 'hay', 
 959: 'carbonara', 
 960: 'chocolate_sauce, chocolate_syrup', 
 961: 'dough', 
 962: 'meat_loaf, meatloaf', 
 963: 'pizza, pizza_pie', 
 964: 'potpie', 
 965: 'burrito', 
 966: 'red_wine', 
 967: 'espresso', 
 968: 'cup', 
 969: 'eggnog', 
 970: 'alp', 
 971: 'bubble', 
 972: 'cliff, drop, drop-off', 
 973: 'coral_reef', 
 974: 'geyser', 
 975: 'lakeside, lakeshore', 
 976: 'promontory, headland, head, foreland', 
 977: 'sandbar, sand_bar', 
 978: 'seashore, coast, seacoast, sea-coast', 
 979: 'valley, vale', 
 980: 'volcano', 
 981: 'ballplayer, baseball_player', 
 982: 'groom, bridegroom', 
 983: 'scuba_diver', 
 984: 'rapeseed', 
 985: 'daisy', 
 986: "yellow_lady's_slipper, yellow_lady-slipper, Cypripedium_calceolus, Cypripedium_parviflorum", 
 987: 'corn', 
 988: 'acorn', 
 989: 'hip, rose_hip, rosehip', 
 990: 'buckeye, horse_chestnut, conker', 
 991: 'coral_fungus', 
 992: 'agaric', 
 993: 'gyromitra', 
 994: 'stinkhorn, carrion_fungus', 
 995: 'earthstar', 
 996: 'hen-of-the-woods, hen_of_the_woods, Polyporus_frondosus, Grifola_frondosa', 
 997: 'bolete', 
 998: 'ear, spike, capitulum', 
 999: 'toilet_tissue, toilet_paper, bathroom_tissue'}